USE university_db;

DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    email VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(256) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    group_code VARCHAR(20),
    role VARCHAR(20) NOT NULL DEFAULT 'student',
    faculty_id INT,
    FOREIGN KEY (faculty_id) REFERENCES faculties(id) ON DELETE SET NULL
);

INSERT INTO users (`id`, `username`, `email`, `full_name`, `role`, `password_hash`, `group_code`, `faculty_id`) VALUES (1, 'admin', 'admin@pnu.edu.ua', 'Адміністратор ПНУ', 'admin', 'admin', NULL, 1);

INSERT INTO users VALUES (2, 'student1', 'yuliya.yaremchuk1@pnu.edu.ua', 'Яремчук Юлія', 'ІСТ-43', 'student', 'pass', 1);
INSERT INTO users VALUES (3, 'student2', 'andrii.pavliuk2@pnu.edu.ua', 'Павлюк Андрій', 'ІСТ-33', 'student', 'pass', 3);
INSERT INTO users VALUES (4, 'student3', 'yaroslav.savchuk3@pnu.edu.ua', 'Савчук Ярослав', 'БІО-13', 'student', 'pass', 7);
INSERT INTO users VALUES (5, 'student4', 'nadiia.tkachuk4@pnu.edu.ua', 'Ткачук Надія', 'ПО-32', 'student', 'pass', 1);
INSERT INTO users VALUES (6, 'student5', 'ivan.melnyk5@pnu.edu.ua', 'Мельник Іван', 'ФВ-11', 'student', 'pass', 1);
INSERT INTO users VALUES (7, 'student6', 'anna.oliinyk6@pnu.edu.ua', 'Олійник Анна', 'ФВ-12', 'student', 'pass', 6);
INSERT INTO users VALUES (8, 'student7', 'daryna.oliinyk7@pnu.edu.ua', 'Олійник Дарина', 'КН-43', 'student', 'pass', 1);
INSERT INTO users VALUES (9, 'student8', 'nadiia.pavliuk8@pnu.edu.ua', 'Павлюк Надія', 'ФВ-31', 'student', 'pass', 6);
INSERT INTO users VALUES (10, 'student9', 'andrii.tkachuk9@pnu.edu.ua', 'Ткачук Андрій', 'ПР-13', 'student', 'pass', 2);
INSERT INTO users VALUES (11, 'student10', 'anna.oliinyk10@pnu.edu.ua', 'Олійник Анна', 'ПО-42', 'student', 'pass', 5);
INSERT INTO users VALUES (12, 'student11', 'andrii.kushnir11@pnu.edu.ua', 'Кушнір Андрій', 'БІО-32', 'student', 'pass', 3);
INSERT INTO users VALUES (13, 'student12', 'anna.boiko12@pnu.edu.ua', 'Бойко Анна', 'ФВ-33', 'student', 'pass', 3);
INSERT INTO users VALUES (14, 'student13', 'yaroslav.polishchuk13@pnu.edu.ua', 'Поліщук Ярослав', 'ПО-13', 'student', 'pass', 7);
INSERT INTO users VALUES (15, 'student14', 'oleksandr.havryliuk14@pnu.edu.ua', 'Гаврилюк Олександр', 'ЕК-12', 'student', 'pass', 1);
INSERT INTO users VALUES (16, 'student15', 'sofiia.polishchuk15@pnu.edu.ua', 'Поліщук Софія', 'М-12', 'student', 'pass', 4);
INSERT INTO users VALUES (17, 'student16', 'dmytro.kushnir16@pnu.edu.ua', 'Кушнір Дмитро', 'АНГ-11', 'student', 'pass', 1);
INSERT INTO users VALUES (18, 'student17', 'oleh.oliinyk17@pnu.edu.ua', 'Олійник Олег', 'М-22', 'student', 'pass', 6);
INSERT INTO users VALUES (19, 'student18', 'dmytro.havryliuk18@pnu.edu.ua', 'Гаврилюк Дмитро', 'ПО-42', 'student', 'pass', 4);
INSERT INTO users VALUES (20, 'student19', 'yaroslav.pavliuk19@pnu.edu.ua', 'Павлюк Ярослав', 'ФВ-33', 'student', 'pass', 8);
INSERT INTO users VALUES (21, 'student20', 'sofiia.kovalenko20@pnu.edu.ua', 'Коваленко Софія', 'ФВ-33', 'student', 'pass', 1);
INSERT INTO users VALUES (22, 'student21', 'olena.oliinyk21@pnu.edu.ua', 'Олійник Олена', 'ПР-22', 'student', 'pass', 8);
INSERT INTO users VALUES (23, 'student22', 'oleksandr.kravchuk22@pnu.edu.ua', 'Кравчук Олександр', 'М-21', 'student', 'pass', 8);
INSERT INTO users VALUES (24, 'student23', 'maksym.savchuk23@pnu.edu.ua', 'Савчук Максим', 'ФВ-23', 'student', 'pass', 4);
INSERT INTO users VALUES (25, 'student24', 'vasyl.savchuk24@pnu.edu.ua', 'Савчук Василь', 'БІО-11', 'student', 'pass', 7);
INSERT INTO users VALUES (26, 'student25', 'olena.tkachuk25@pnu.edu.ua', 'Ткачук Олена', 'ПО-21', 'student', 'pass', 7);
INSERT INTO users VALUES (27, 'student26', 'oksana.boiko26@pnu.edu.ua', 'Бойко Оксана', 'ІПЗ-33', 'student', 'pass', 4);
INSERT INTO users VALUES (28, 'student27', 'anna.havryliuk27@pnu.edu.ua', 'Гаврилюк Анна', 'ФВ-21', 'student', 'pass', 8);
INSERT INTO users VALUES (29, 'student28', 'sofiia.yaremchuk28@pnu.edu.ua', 'Яремчук Софія', 'ПО-12', 'student', 'pass', 4);
INSERT INTO users VALUES (30, 'student29', 'olena.pavliuk29@pnu.edu.ua', 'Павлюк Олена', 'АНГ-22', 'student', 'pass', 5);
INSERT INTO users VALUES (31, 'student30', 'oleksandr.polishchuk30@pnu.edu.ua', 'Поліщук Олександр', 'ПР-43', 'student', 'pass', 1);
INSERT INTO users VALUES (32, 'student31', 'roman.koval31@pnu.edu.ua', 'Коваль Роман', 'ІСТ-11', 'student', 'pass', 1);
INSERT INTO users VALUES (33, 'student32', 'viktoriia.bondar32@pnu.edu.ua', 'Бондар Вікторія', 'ЕК-31', 'student', 'pass', 2);
INSERT INTO users VALUES (34, 'student33', 'denys.moroz33@pnu.edu.ua', 'Мороз Денис', 'ФВ-22', 'student', 'pass', 3);
INSERT INTO users VALUES (35, 'student34', 'kateryna.lysenko34@pnu.edu.ua', 'Лисенко Катерина', 'АНГ-41', 'student', 'pass', 4);
INSERT INTO users VALUES (36, 'student35', 'maksym.shvets35@pnu.edu.ua', 'Швець Максим', 'ІСТ-22', 'student', 'pass', 5);
INSERT INTO users VALUES (37, 'student36', 'alina.petrenko36@pnu.edu.ua', 'Петренко Аліна', 'БІО-41', 'student', 'pass', 6);
INSERT INTO users VALUES (38, 'student37', 'bohdan.litvinov37@pnu.edu.ua', 'Літвінов Богдан', 'ПО-33', 'student', 'pass', 7);
INSERT INTO users VALUES (39, 'student38', 'maria.rudnitska38@pnu.edu.ua', 'Рудницька Марія', 'ПР-11', 'student', 'pass', 8);
INSERT INTO users VALUES (40, 'student39', 'vitalii.klymneko39@pnu.edu.ua', 'Клименко Віталій', 'ІПЗ-12', 'student', 'pass', 1);
INSERT INTO users VALUES (41, 'student40', 'yana.zhuk40@pnu.edu.ua', 'Жук Яна', 'ЕК-22', 'student', 'pass', 2);
INSERT INTO users VALUES (42, 'student41', 'nazar.honchar41@pnu.edu.ua', 'Гончар Назар', 'ФВ-41', 'student', 'pass', 3);
INSERT INTO users VALUES (43, 'student42', 'yuliia.zakharova42@pnu.edu.ua', 'Захарова Юлія', 'НІМ-31', 'student', 'pass', 4);
INSERT INTO users VALUES (44, 'student43', 'volodymyr.panasenko43@pnu.edu.ua', 'Панасенко Володимир', 'ПОЛ-21', 'student', 'pass', 5);
INSERT INTO users VALUES (45, 'student44', 'olha.fedorova44@pnu.edu.ua', 'Федорова Ольга', 'ГЕО-13', 'student', 'pass', 6);
INSERT INTO users VALUES (46, 'student45', 'dmytro.syrota45@pnu.edu.ua', 'Сирота Дмитро', 'ПО-11', 'student', 'pass', 7);
INSERT INTO users VALUES (47, 'student46', 'tetiana.martynenko46@pnu.edu.ua', 'Мартиненко Тетяна', 'ПР-33', 'student', 'pass', 8);
INSERT INTO users VALUES (48, 'student47', 'artem.solovei47@pnu.edu.ua', 'Соловей Артем', 'КН-21', 'student', 'pass', 1);
INSERT INTO users VALUES (49, 'student48', 'oksana.kyrylenko48@pnu.edu.ua', 'Кириленко Оксана', 'ОБЛ-12', 'student', 'pass', 2);
INSERT INTO users VALUES (50, 'student49', 'rostyslav.zayets49@pnu.edu.ua', 'Заєць Ростислав', 'ФВ-13', 'student', 'pass', 3);
INSERT INTO users VALUES (51, 'student50', 'iryna.osypenko50@pnu.edu.ua', 'Осипенко Ірина', 'АНГ-33', 'student', 'pass', 4);
INSERT INTO users VALUES (52, 'student51', 'mykola.doroshenko51@pnu.edu.ua', 'Дорошенко Микола', 'ІСТ-41', 'student', 'pass', 5);
INSERT INTO users VALUES (53, 'student52', 'nataliia.lytvenko52@pnu.edu.ua', 'Литвенко Наталія', 'ХІМ-22', 'student', 'pass', 6);
INSERT INTO users VALUES (54, 'student53', 'serhii.boiko53@pnu.edu.ua', 'Бойко Сергій', 'ПО-23', 'student', 'pass', 7);
INSERT INTO users VALUES (55, 'student54', 'anastasiia.melnyk54@pnu.edu.ua', 'Мельник Анастасія', 'ПР-41', 'student', 'pass', 8);
INSERT INTO users VALUES (56, 'student55', 'yevhen.kozlov55@pnu.edu.ua', 'Козлов Євген', 'МАТ-31', 'student', 'pass', 1);
INSERT INTO users VALUES (57, 'student56', 'liubov.stepanenko56@pnu.edu.ua', 'Степаненко Любов', 'ЕК-43', 'student', 'pass', 2);
INSERT INTO users VALUES (58, 'student57', 'vadym.yurchenko57@pnu.edu.ua', 'Юрченко Вадим', 'ФВ-32', 'student', 'pass', 3);
INSERT INTO users VALUES (59, 'student58', 'halyna.kostenko58@pnu.edu.ua', 'Костенко Галина', 'ФРА-11', 'student', 'pass', 4);
INSERT INTO users VALUES (60, 'student59', 'oleg.tarasenko59@pnu.edu.ua', 'Тарасенко Олег', 'ПОЛ-33', 'student', 'pass', 5);
INSERT INTO users VALUES (61, 'student60', 'svitlana.hryhorenko60@pnu.edu.ua', 'Григоренко Світлана', 'БІО-23', 'student', 'pass', 6);
INSERT INTO users VALUES (62, 'student61', 'andrii.bondarenko61@pnu.edu.ua', 'Бондаренко Андрій', 'ПО-41', 'student', 'pass', 7);
INSERT INTO users VALUES (63, 'student62', 'olena.karpenko62@pnu.edu.ua', 'Карпенко Олена', 'ПР-21', 'student', 'pass', 8);
INSERT INTO users VALUES (64, 'student63', 'viktor.semenenko63@pnu.edu.ua', 'Семененко Віктор', 'ІПЗ-22', 'student', 'pass', 1);
INSERT INTO users VALUES (65, 'student64', 'marina.onyshchenko64@pnu.edu.ua', 'Онищенко Марина', 'МЕН-11', 'student', 'pass', 2);
INSERT INTO users VALUES (66, 'student65', 'pavlo.dudka65@pnu.edu.ua', 'Дудка Павло', 'ФВ-21', 'student', 'pass', 3);
INSERT INTO users VALUES (67, 'student66', 'krystyna.voloshyn66@pnu.edu.ua', 'Волошин Кристина', 'АНГ-13', 'student', 'pass', 4);
INSERT INTO users VALUES (68, 'student67', 'taras.savchenko67@pnu.edu.ua', 'Савченко Тарас', 'ІСТ-32', 'student', 'pass', 5);
INSERT INTO users VALUES (69, 'student68', 'alla.romanenko68@pnu.edu.ua', 'Романенко Алла', 'ГЕО-31', 'student', 'pass', 6);
INSERT INTO users VALUES (70, 'student69', 'ivan.mykhailenko69@pnu.edu.ua', 'Михайленко Іван', 'ПО-12', 'student', 'pass', 7);
INSERT INTO users VALUES (71, 'student70', 'veronika.lysak70@pnu.edu.ua', 'Лисак Вероніка', 'ПР-12', 'student', 'pass', 8);
INSERT INTO users VALUES (72, 'student71', 'roman.bilous71@pnu.edu.ua', 'Білоус Роман', 'КН-11', 'student', 'pass', 1);
INSERT INTO users VALUES (73, 'student72', 'daria.pavlenko72@pnu.edu.ua', 'Павленко Дарія', 'ФІН-33', 'student', 'pass', 2);
INSERT INTO users VALUES (74, 'student73', 'maksym.tkachenko73@pnu.edu.ua', 'Ткаченко Максим', 'ФВ-42', 'student', 'pass', 3);
INSERT INTO users VALUES (75, 'student74', 'yuliia.popova74@pnu.edu.ua', 'Попова Юлія', 'НІМ-21', 'student', 'pass', 4);
INSERT INTO users VALUES (76, 'student75', 'serhii.denysenko75@pnu.edu.ua', 'Денисенко Сергій', 'ПОЛ-12', 'student', 'pass', 5);
INSERT INTO users VALUES (77, 'student76', 'olha.vasylenko76@pnu.edu.ua', 'Василенко Ольга', 'ХІМ-41', 'student', 'pass', 6);
INSERT INTO users VALUES (78, 'student77', 'dmytro.kovalenko77@pnu.edu.ua', 'Коваленко Дмитро', 'ПО-31', 'student', 'pass', 7);
INSERT INTO users VALUES (79, 'student78', 'tetiana.shevchenko78@pnu.edu.ua', 'Шевченко Тетяна', 'ПР-32', 'student', 'pass', 8);
INSERT INTO users VALUES (80, 'student79', 'artem.ivanov79@pnu.edu.ua', 'Іванов Артем', 'МАТ-23', 'student', 'pass', 1);
INSERT INTO users VALUES (81, 'student80', 'oksana.kulyk80@pnu.edu.ua', 'Кулик Оксана', 'ЕК-11', 'student', 'pass', 2);
INSERT INTO users VALUES (82, 'student81', 'rostyslav.lytvyneko81@pnu.edu.ua', 'Литвиненко Ростислав', 'ФВ-12', 'student', 'pass', 3);
INSERT INTO users VALUES (83, 'student82', 'iryna.babenko82@pnu.edu.ua', 'Бабенко Ірина', 'АНГ-21', 'student', 'pass', 4);
INSERT INTO users VALUES (84, 'student83', 'mykola.rud83@pnu.edu.ua', 'Рудь Микола', 'ІСТ-21', 'student', 'pass', 5);
INSERT INTO users VALUES (85, 'student84', 'nataliia.kryvonos84@pnu.edu.ua', 'Кривонос Наталія', 'БІО-12', 'student', 'pass', 6);
INSERT INTO users VALUES (86, 'student85', 'yevhen.nazarenko85@pnu.edu.ua', 'Назаренко Євген', 'ПО-22', 'student', 'pass', 7);
INSERT INTO users VALUES (87, 'student86', 'anastasiia.polishchuk86@pnu.edu.ua', 'Поліщук Анастасія', 'ПР-42', 'student', 'pass', 8);
INSERT INTO users VALUES (88, 'student87', 'vadym.yakovenko87@pnu.edu.ua', 'Яковенко Вадим', 'ІСТ-12', 'student', 'pass', 1);
INSERT INTO users VALUES (89, 'student88', 'liubov.fedorchuk88@pnu.edu.ua', 'Федорчук Любов', 'МЕН-23', 'student', 'pass', 2);
INSERT INTO users VALUES (90, 'student89', 'halyna.prykhodko89@pnu.edu.ua', 'Приходько Галина', 'ФВ-31', 'student', 'pass', 3);
INSERT INTO users VALUES (91, 'student90', 'oleg.shymko90@pnu.edu.ua', 'Шимко Олег', 'ФРА-22', 'student', 'pass', 4);
INSERT INTO users VALUES (92, 'student91', 'svitlana.moskalenko91@pnu.edu.ua', 'Москаленко Світлана', 'ПОЛ-13', 'student', 'pass', 5);
INSERT INTO users VALUES (93, 'student92', 'andrii.antonenko92@pnu.edu.ua', 'Антоненко Андрій', 'ГЕО-42', 'student', 'pass', 6);
INSERT INTO users VALUES (94, 'student93', 'olena.kravchenko93@pnu.edu.ua', 'Кравченко Олена', 'ПО-43', 'student', 'pass', 7);
INSERT INTO users VALUES (95, 'student94', 'viktor.pohrebniak94@pnu.edu.ua', 'Погребняк Віктор', 'ПР-11', 'student', 'pass', 8);
INSERT INTO users VALUES (96, 'student95', 'marina.sydorenko95@pnu.edu.ua', 'Сидоренко Марина', 'ІПЗ-32', 'student', 'pass', 1);
INSERT INTO users VALUES (97, 'student96', 'pavlo.koshovyi96@pnu.edu.ua', 'Кошовий Павло', 'ФІН-12', 'student', 'pass', 2);
INSERT INTO users VALUES (98, 'student97', 'krystyna.didenko97@pnu.edu.ua', 'Діденко Кристина', 'ФВ-22', 'student', 'pass', 3);
INSERT INTO users VALUES (99, 'student98', 'taras.shapoval98@pnu.edu.ua', 'Шаповал Тарас', 'АНГ-31', 'student', 'pass', 4);
INSERT INTO users VALUES (100, 'student99', 'alla.holub99@pnu.edu.ua', 'Голуб Алла', 'ІСТ-31', 'student', 'pass', 5);
INSERT INTO users VALUES (101, 'student100', 'ivan.protsenko100@pnu.edu.ua', 'Проценко Іван', 'ХІМ-13', 'student', 'pass', 6);
INSERT INTO users VALUES (102, 'student101', 'veronika.klymchuk101@pnu.edu.ua', 'Климчук Вероніка', 'ПО-11', 'student', 'pass', 7);
INSERT INTO users VALUES (103, 'student102', 'roman.ovcharenko102@pnu.edu.ua', 'Овчаренко Роман', 'ПР-23', 'student', 'pass', 8);
INSERT INTO users VALUES (104, 'student103', 'daria.marchenko103@pnu.edu.ua', 'Марченко Дарія', 'КН-32', 'student', 'pass', 1);
INSERT INTO users VALUES (105, 'student104', 'maksym.tyshchenko104@pnu.edu.ua', 'Тищенко Максим', 'ОБЛ-31', 'student', 'pass', 2);
INSERT INTO users VALUES (106, 'student105', 'yuliia.yarova105@pnu.edu.ua', 'Ярова Юлія', 'ФВ-43', 'student', 'pass', 3);
INSERT INTO users VALUES (107, 'student106', 'serhii.novikov106@pnu.edu.ua', 'Новіков Сергій', 'НІМ-12', 'student', 'pass', 4);
INSERT INTO users VALUES (108, 'student107', 'olha.makarenko107@pnu.edu.ua', 'Макаренко Ольга', 'ПОЛ-42', 'student', 'pass', 5);
INSERT INTO users VALUES (109, 'student108', 'dmytro.bondar108@pnu.edu.ua', 'Бондар Дмитро', 'БІО-31', 'student', 'pass', 6);
INSERT INTO users VALUES (110, 'student109', 'tetiana.shulha109@pnu.edu.ua', 'Шульга Тетяна', 'ПО-32', 'student', 'pass', 7);
INSERT INTO users VALUES (111, 'student110', 'artem.zinchenko110@pnu.edu.ua', 'Зінченко Артем', 'ПР-31', 'student', 'pass', 8);
INSERT INTO users VALUES (112, 'student111', 'oksana.lytvyn111@pnu.edu.ua', 'Литвин Оксана', 'МАТ-42', 'student', 'pass', 1);
INSERT INTO users VALUES (113, 'student112', 'rostyslav.zakharenko112@pnu.edu.ua', 'Захаренко Ростислав', 'ЕК-21', 'student', 'pass', 2);
INSERT INTO users VALUES (114, 'student113', 'iryna.kolomiiets113@pnu.edu.ua', 'Коломієць Ірина', 'ФВ-11', 'student', 'pass', 3);
INSERT INTO users VALUES (115, 'student114', 'mykola.soroka114@pnu.edu.ua', 'Сорока Микола', 'АНГ-42', 'student', 'pass', 4);
INSERT INTO users VALUES (116, 'student115', 'nataliia.pylypenko115@pnu.edu.ua', 'Пилипенко Наталія', 'ІСТ-23', 'student', 'pass', 5);
INSERT INTO users VALUES (117, 'student116', 'yevhen.honcharenko116@pnu.edu.ua', 'Гончаренко Євген', 'ГЕО-12', 'student', 'pass', 6);
INSERT INTO users VALUES (118, 'student117', 'anastasiia.vlasenko117@pnu.edu.ua', 'Власенко Анастасія', 'ПО-21', 'student', 'pass', 7);
INSERT INTO users VALUES (119, 'student118', 'vadym.derevianko118@pnu.edu.ua', 'Дерев\'янко Вадим', 'ПР-41', 'student', 'pass', 8);
INSERT INTO users VALUES (120, 'student119', 'liubov.kornienko119@pnu.edu.ua', 'Корнієнко Любов', 'ІПЗ-41', 'student', 'pass', 1);
INSERT INTO users VALUES (121, 'student120', 'halyna.kalinina120@pnu.edu.ua', 'Калініна Галина', 'МЕН-32', 'student', 'pass', 2);
INSERT INTO users VALUES (122, 'student121', 'oleg.myroshnychenko121@pnu.edu.ua', 'Мирошниченко Олег', 'ФВ-33', 'student', 'pass', 3);
INSERT INTO users VALUES (123, 'student122', 'svitlana.sydoruk122@pnu.edu.ua', 'Сидорук Світлана', 'ФРА-31', 'student', 'pass', 4);
INSERT INTO users VALUES (124, 'student123', 'andrii.semenyuk123@pnu.edu.ua', 'Семенюк Андрій', 'ПОЛ-23', 'student', 'pass', 5);
INSERT INTO users VALUES (125, 'student124', 'olena.romaniuk124@pnu.edu.ua', 'Романюк Олена', 'ХІМ-32', 'student', 'pass', 6);
INSERT INTO users VALUES (126, 'student125', 'viktor.voitsekhovskyi125@pnu.edu.ua', 'Войцеховський Віктор', 'ПО-41', 'student', 'pass', 7);
INSERT INTO users VALUES (127, 'student126', 'marina.kucherenko126@pnu.edu.ua', 'Кучеренко Марина', 'ПР-13', 'student', 'pass', 8);
INSERT INTO users VALUES (128, 'student127', 'pavlo.kostenko127@pnu.edu.ua', 'Костенко Павло', 'ІСТ-42', 'student', 'pass', 1);
INSERT INTO users VALUES (129, 'student128', 'krystyna.danylenko128@pnu.edu.ua', 'Даниленко Кристина', 'ФІН-21', 'student', 'pass', 2);
INSERT INTO users VALUES (130, 'student129', 'taras.kravets129@pnu.edu.ua', 'Кравець Тарас', 'ФВ-21', 'student', 'pass', 3);
INSERT INTO users VALUES (131, 'student130', 'alla.moiseienko130@pnu.edu.ua', 'Моісеєнко Алла', 'АНГ-12', 'student', 'pass', 4);
INSERT INTO users VALUES (132, 'student131', 'ivan.lytvynenko131@pnu.edu.ua', 'Литвиненко Іван', 'ІСТ-13', 'student', 'pass', 5);
INSERT INTO users VALUES (133, 'student132', 'veronika.zhuravlova132@pnu.edu.ua', 'Журавльова Вероніка', 'БІО-42', 'student', 'pass', 6);
INSERT INTO users VALUES (134, 'student133', 'roman.panasiuk133@pnu.edu.ua', 'Панасюк Роман', 'ПО-13', 'student', 'pass', 7);
INSERT INTO users VALUES (135, 'student134', 'daria.fedorenko134@pnu.edu.ua', 'Федоренко Дарія', 'ПР-21', 'student', 'pass', 8);
INSERT INTO users VALUES (136, 'student135', 'maksym.poplavskyi135@pnu.edu.ua', 'Поплавський Максим', 'КН-41', 'student', 'pass', 1);
INSERT INTO users VALUES (137, 'student136', 'yuliia.kolesnyk136@pnu.edu.ua', 'Колесник Юлія', 'ЕК-33', 'student', 'pass', 2);
INSERT INTO users VALUES (138, 'student137', 'serhii.zhylin137@pnu.edu.ua', 'Жилін Сергій', 'ФВ-41', 'student', 'pass', 3);
INSERT INTO users VALUES (139, 'student138', 'olha.hrytsenko138@pnu.edu.ua', 'Гриценко Ольга', 'НІМ-41', 'student', 'pass', 4);
INSERT INTO users VALUES (140, 'student139', 'dmytro.chernenko139@pnu.edu.ua', 'Черненко Дмитро', 'ПОЛ-31', 'student', 'pass', 5);
INSERT INTO users VALUES (141, 'student140', 'tetiana.stepaniuk140@pnu.edu.ua', 'Степанюк Тетяна', 'ГЕО-21', 'student', 'pass', 6);
INSERT INTO users VALUES (142, 'student141', 'artem.kyrychenko141@pnu.edu.ua', 'Кириченко Артем', 'ПО-33', 'student', 'pass', 7);
INSERT INTO users VALUES (143, 'student142', 'oksana.melnychenko142@pnu.edu.ua', 'Мельниченко Оксана', 'ПР-33', 'student', 'pass', 8);
INSERT INTO users VALUES (144, 'student143', 'rostyslav.bilokin143@pnu.edu.ua', 'Білокінь Ростислав', 'ІПЗ-11', 'student', 'pass', 1);
INSERT INTO users VALUES (145, 'student144', 'iryna.savyn144@pnu.edu.ua', 'Савин Ірина', 'ОБЛ-22', 'student', 'pass', 2);
INSERT INTO users VALUES (146, 'student145', 'mykola.volkov145@pnu.edu.ua', 'Волков Микола', 'ФВ-13', 'student', 'pass', 3);
INSERT INTO users VALUES (147, 'student146', 'nataliia.soboleva146@pnu.edu.ua', 'Соболєва Наталія', 'АНГ-23', 'student', 'pass', 4);
INSERT INTO users VALUES (148, 'student147', 'yevhen.titov147@pnu.edu.ua', 'Тітов Євген', 'ІСТ-33', 'student', 'pass', 5);
INSERT INTO users VALUES (149, 'student148', 'anastasiia.soloviova148@pnu.edu.ua', 'Соловйова Анастасія', 'ХІМ-23', 'student', 'pass', 6);
INSERT INTO users VALUES (150, 'student149', 'vadym.yermolenko149@pnu.edu.ua', 'Єрмоленко Вадим', 'ПО-22', 'student', 'pass', 7);