USE university_db;

DROP TABLE IF EXISTS records;

CREATE TABLE records (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    result_value VARCHAR(100) NOT NULL,
    event_date DATE NOT NULL,
    status VARCHAR(20) DEFAULT 'pending',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    user_id INT,
    team_id INT,
    category_id INT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE SET NULL,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
);

INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Стажування в Європарламенті.', 'Успішно завершено', 'approved', '2026-02-03 20:35:39', NULL, '3', '5', 'Стажування в Європарламенті (Командний залік)', '1', '2023-08-26');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Благодійний ярмарок на підтримку ЗСУ.', 'Зібрано 200 тис. грн', 'rejected', '2026-02-03 20:35:40', '17', NULL, '6', 'Благодійний ярмарок на підтримку ЗСУ', '2', '2024-02-22');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Мовний конкурс імені Петра Яцика.', 'Переможець етапу', 'approved', '2026-02-03 20:35:40', '17', NULL, '2', 'Мовний конкурс імені Петра Яцика', '3', '2026-11-05');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Erasmus+ Scholarship (Poland).', 'Отримано грант', 'approved', '2026-02-03 20:35:40', '5', NULL, '5', 'Erasmus+ Scholarship (Poland)', '4', '2024-10-18');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Хакатон "Frankivsk Tech".', 'Гран-прі', 'approved', '2026-02-03 20:35:40', '12', NULL, '3', 'Хакатон "Frankivsk Tech"', '5', '2026-11-08');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Erasmus+ Scholarship (Poland).', 'Отримано грант', 'approved', '2026-02-03 20:35:40', '17', NULL, '5', 'Erasmus+ Scholarship (Poland)', '6', '2024-03-04');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Найбільша кількість волонтерських годин.', 'Рекорд факультету', 'approved', '2026-02-03 20:35:40', '31', NULL, '6', 'Найбільша кількість волонтерських годин', '7', '2026-08-12');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Конкурс наукових робіт Фонду Пінчука.', 'Лауреат', 'approved', '2026-02-03 20:35:40', '27', NULL, '2', 'Конкурс наукових робіт Фонду Пінчука', '8', '2024-02-20');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Конкурс наукових робіт Фонду Пінчука.', 'Лауреат', 'approved', '2026-02-03 20:35:40', '5', NULL, '2', 'Конкурс наукових робіт Фонду Пінчука', '9', '2025-09-07');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Танцювальний батл між факультетами.', 'Кубок глядачів', 'approved', '2026-02-03 20:35:40', '11', NULL, '4', 'Танцювальний батл між факультетами', '10', '2026-09-18');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Найбільша кількість волонтерських годин.', 'Рекорд факультету', 'approved', '2026-02-03 20:35:40', NULL, '5', '6', 'Найбільша кількість волонтерських годин (Командний залік)', '11', '2023-12-11');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Студентська олімпіада з програмування.', 'Диплом 1 ступеня', 'approved', '2026-02-03 20:35:40', '14', NULL, '3', 'Студентська олімпіада з програмування', '12', '2026-12-10');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Еко-акція "Чисті Карпати".', 'Подяка від ректора', 'pending', '2026-02-03 20:35:40', '22', NULL, '6', 'Еко-акція "Чисті Карпати"', '13', '2023-08-11');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Голос Університету.', '1 місце', 'approved', '2026-02-03 20:35:40', '15', NULL, '4', 'Голос Університету', '14', '2026-02-20');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Міс ПНУ 2024.', 'Титул Міс Грація', 'approved', '2026-02-03 20:35:41', '29', NULL, '4', 'Міс ПНУ 2024', '15', '2023-11-15');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Найбільша кількість волонтерських годин.', 'Рекорд факультету', 'approved', '2026-02-03 20:35:41', '17', NULL, '6', 'Найбільша кількість волонтерських годин', '16', '2023-11-16');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Міжнародний хакатон NASA Space Apps.', 'Global Nominee', 'approved', '2026-02-03 20:35:41', '11', NULL, '5', 'Міжнародний хакатон NASA Space Apps', '17', '2024-09-10');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Наукова конференція молодих вчених.', 'Краща доповідь', 'pending', '2026-02-03 20:35:41', '16', NULL, '2', 'Наукова конференція молодих вчених', '18', '2025-09-15');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Конкурс наукових робіт Фонду Пінчука.', 'Лауреат', 'pending', '2026-02-03 20:35:41', '3', NULL, '2', 'Конкурс наукових робіт Фонду Пінчука', '19', '2026-11-25');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Голос Університету.', '1 місце', 'pending', '2026-02-03 20:35:41', '2', NULL, '4', 'Голос Університету', '20', '2023-04-21');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Erasmus+ Scholarship (Poland).', 'Отримано грант', 'pending', '2026-02-03 20:35:41', NULL, '5', '5', 'Erasmus+ Scholarship (Poland) (Командний залік)', '21', '2024-12-06');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Мовний конкурс імені Петра Яцика.', 'Переможець етапу', 'rejected', '2026-02-03 20:35:41', '18', NULL, '2', 'Мовний конкурс імені Петра Яцика', '22', '2023-02-05');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Конкурс наукових робіт Фонду Пінчука.', 'Лауреат', 'approved', '2026-02-03 20:35:41', '25', NULL, '2', 'Конкурс наукових робіт Фонду Пінчука', '23', '2023-08-10');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Міжнародний хакатон NASA Space Apps.', 'Global Nominee', 'approved', '2026-02-03 20:35:41', '26', NULL, '5', 'Міжнародний хакатон NASA Space Apps', '24', '2024-08-28');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Стажування в Європарламенті.', 'Успішно завершено', 'approved', '2026-02-03 20:35:41', '21', NULL, '5', 'Стажування в Європарламенті', '25', '2025-09-11');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Стажування в Європарламенті.', 'Успішно завершено', 'pending', '2026-02-03 20:35:41', '30', NULL, '5', 'Стажування в Європарламенті', '26', '2023-04-06');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Турнір з шахів пам\'яті Стефаника.', 'Переможець', 'approved', '2026-02-03 20:35:41', '17', NULL, '1', 'Турнір з шахів пам\'яті Стефаника', '27', '2026-07-15');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Найбільша кількість волонтерських годин.', 'Рекорд факультету', 'approved', '2026-02-03 20:35:41', '2', NULL, '6', 'Найбільша кількість волонтерських годин', '28', '2026-12-21');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Міжнародний хакатон NASA Space Apps.', 'Global Nominee', 'approved', '2026-02-03 20:35:41', '24', NULL, '5', 'Міжнародний хакатон NASA Space Apps', '29', '2025-06-12');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Мовний конкурс імені Петра Яцика.', 'Переможець етапу', 'approved', '2026-02-03 20:35:42', '11', NULL, '2', 'Мовний конкурс імені Петра Яцика', '30', '2023-06-10');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Хакатон "Frankivsk Tech".', 'Гран-прі', 'approved', '2026-02-03 20:35:42', NULL, '4', '3', 'Хакатон "Frankivsk Tech" (Командний залік)', '31', '2025-03-28');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Літературний вечір "Поезія Франківська".', 'Відзнака', 'pending', '2026-02-03 20:35:42', '26', NULL, '4', 'Літературний вечір "Поезія Франківська"', '32', '2024-10-19');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Чемпіонат області з баскетболу.', '2 місце', 'rejected', '2026-02-03 20:35:42', '21', NULL, '1', 'Чемпіонат області з баскетболу', '33', '2024-12-06');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Чемпіонат області з баскетболу.', '2 місце', 'rejected', '2026-02-03 20:35:42', '2', NULL, '1', 'Чемпіонат області з баскетболу', '34', '2026-04-07');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Кубок Ректора з футзалу.', '1 місце', 'rejected', '2026-02-03 20:35:42', '9', NULL, '1', 'Кубок Ректора з футзалу', '35', '2024-09-26');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Хакатон "Frankivsk Tech".', 'Гран-прі', 'approved', '2026-02-03 20:35:42', '2', NULL, '3', 'Хакатон "Frankivsk Tech"', '36', '2025-12-28');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Благодійний ярмарок на підтримку ЗСУ.', 'Зібрано 200 тис. грн', 'rejected', '2026-02-03 20:35:42', '23', NULL, '6', 'Благодійний ярмарок на підтримку ЗСУ', '37', '2026-06-28');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Еко-акція "Чисті Карпати".', 'Подяка від ректора', 'approved', '2026-02-03 20:35:42', '4', NULL, '6', 'Еко-акція "Чисті Карпати"', '38', '2023-06-23');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Студентська олімпіада з програмування.', 'Диплом 1 ступеня', 'approved', '2026-02-03 20:35:42', '14', NULL, '3', 'Студентська олімпіада з програмування', '39', '2026-12-24');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Конкурс стартапів "Ідеї майбутнього".', 'Грант на розробку', 'pending', '2026-02-03 20:35:42', '8', NULL, '3', 'Конкурс стартапів "Ідеї майбутнього"', '40', '2025-01-02');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Конкурс наукових робіт Фонду Пінчука.', 'Лауреат', 'pending', '2026-02-03 20:35:42', NULL, '5', '2', 'Конкурс наукових робіт Фонду Пінчука (Командний залік)', '41', '2025-07-13');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Турнір з шахів пам\'яті Стефаника.', 'Переможець', 'approved', '2026-02-03 20:35:42', '2', NULL, '1', 'Турнір з шахів пам\'яті Стефаника', '42', '2023-07-10');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Голос Університету.', '1 місце', 'approved', '2026-02-03 20:35:42', '7', NULL, '4', 'Голос Університету', '43', '2025-06-16');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Хакатон "Frankivsk Tech".', 'Гран-прі', 'pending', '2026-02-03 20:35:42', '24', NULL, '3', 'Хакатон "Frankivsk Tech"', '44', '2026-08-16');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Google Hash Code (Hub PNU).', 'Топ-10 України', 'pending', '2026-02-03 20:35:43', '17', NULL, '3', 'Google Hash Code (Hub PNU)', '45', '2024-05-07');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Erasmus+ Scholarship (Poland).', 'Отримано грант', 'rejected', '2026-02-03 20:35:43', '27', NULL, '5', 'Erasmus+ Scholarship (Poland)', '46', '2026-05-01');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Літературний вечір "Поезія Франківська".', 'Відзнака', 'approved', '2026-02-03 20:35:43', '24', NULL, '4', 'Літературний вечір "Поезія Франківська"', '47', '2026-01-03');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Наукова конференція молодих вчених.', 'Краща доповідь', 'approved', '2026-02-03 20:35:43', '26', NULL, '2', 'Наукова конференція молодих вчених', '48', '2026-02-21');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Хакатон "Frankivsk Tech".', 'Гран-прі', 'pending', '2026-02-03 20:35:43', '21', NULL, '3', 'Хакатон "Frankivsk Tech"', '49', '2023-05-10');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Літературний вечір "Поезія Франківська".', 'Відзнака', 'approved', '2026-02-03 20:35:43', '4', NULL, '4', 'Літературний вечір "Поезія Франківська"', '50', '2025-08-20');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Танцювальний батл між факультетами.', 'Кубок глядачів', 'pending', '2026-02-03 20:35:43', NULL, '4', '4', 'Танцювальний батл між факультетами (Командний залік)', '51', '2026-09-08');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Благодійний ярмарок на підтримку ЗСУ.', 'Зібрано 200 тис. грн', 'rejected', '2026-02-03 20:35:43', '3', NULL, '6', 'Благодійний ярмарок на підтримку ЗСУ', '52', '2024-10-04');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Стажування в Європарламенті.', 'Успішно завершено', 'approved', '2026-02-03 20:35:43', '12', NULL, '5', 'Стажування в Європарламенті', '53', '2025-02-03');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Кубок Ректора з футзалу.', '1 місце', 'pending', '2026-02-03 20:35:43', '3', NULL, '1', 'Кубок Ректора з футзалу', '54', '2025-03-16');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Танцювальний батл між факультетами.', 'Кубок глядачів', 'rejected', '2026-02-03 20:35:43', '28', NULL, '4', 'Танцювальний батл між факультетами', '55', '2025-08-20');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Літературний вечір "Поезія Франківська".', 'Відзнака', 'pending', '2026-02-03 20:35:43', '29', NULL, '4', 'Літературний вечір "Поезія Франківська"', '56', '2025-03-17');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Наукова конференція молодих вчених.', 'Краща доповідь', 'approved', '2026-02-03 20:35:43', '4', NULL, '2', 'Наукова конференція молодих вчених', '57', '2025-08-13');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Наукова конференція молодих вчених.', 'Краща доповідь', 'approved', '2026-02-03 20:35:43', '11', NULL, '2', 'Наукова конференція молодих вчених', '58', '2023-02-02');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Студентська олімпіада з програмування.', 'Диплом 1 ступеня', 'rejected', '2026-02-03 20:35:43', '3', NULL, '3', 'Студентська олімпіада з програмування', '59', '2024-02-16');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Універсіада: Легка атлетика.', 'Золота медаль', 'approved', '2026-02-03 20:35:44', '26', NULL, '1', 'Універсіада: Легка атлетика', '60', '2026-04-05');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Студентська олімпіада з програмування.', 'Диплом 1 ступеня', 'approved', '2026-02-03 20:35:44', NULL, '3', '3', 'Студентська олімпіада з програмування (Командний залік)', '61', '2024-07-27');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Конкурс наукових робіт Фонду Пінчука.', 'Лауреат', 'pending', '2026-02-03 20:35:44', '14', NULL, '2', 'Конкурс наукових робіт Фонду Пінчука', '62', '2024-12-06');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Голос Університету.', '1 місце', 'approved', '2026-02-03 20:35:44', '18', NULL, '4', 'Голос Університету', '63', '2024-10-12');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Найбільша кількість волонтерських годин.', 'Рекорд факультету', 'pending', '2026-02-03 20:35:44', '30', NULL, '6', 'Найбільша кількість волонтерських годин', '64', '2025-05-10');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Мовний конкурс імені Петра Яцика.', 'Переможець етапу', 'approved', '2026-02-03 20:35:44', '6', NULL, '2', 'Мовний конкурс імені Петра Яцика', '65', '2023-04-27');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Найбільша кількість волонтерських годин.', 'Рекорд факультету', 'approved', '2026-02-03 20:35:44', '10', NULL, '6', 'Найбільша кількість волонтерських годин', '66', '2023-02-28');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Благодійний ярмарок на підтримку ЗСУ.', 'Зібрано 200 тис. грн', 'approved', '2026-02-03 20:35:44', '3', NULL, '6', 'Благодійний ярмарок на підтримку ЗСУ', '67', '2026-11-05');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Танцювальний батл між факультетами.', 'Кубок глядачів', 'pending', '2026-02-03 20:35:44', '29', NULL, '4', 'Танцювальний батл між факультетами', '68', '2024-08-28');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Міжнародний хакатон NASA Space Apps.', 'Global Nominee', 'rejected', '2026-02-03 20:35:44', '29', NULL, '5', 'Міжнародний хакатон NASA Space Apps', '69', '2023-05-16');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Конкурс наукових робіт Фонду Пінчука.', 'Лауреат', 'approved', '2026-02-03 20:35:44', '5', NULL, '2', 'Конкурс наукових робіт Фонду Пінчука', '70', '2024-05-26');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Міжнародний хакатон NASA Space Apps.', 'Global Nominee', 'pending', '2026-02-03 20:35:44', NULL, '2', '5', 'Міжнародний хакатон NASA Space Apps (Командний залік)', '71', '2026-09-02');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Чемпіонат області з баскетболу.', '2 місце', 'rejected', '2026-02-03 20:35:44', '6', NULL, '1', 'Чемпіонат області з баскетболу', '72', '2023-03-08');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Літературний вечір "Поезія Франківська".', 'Відзнака', 'approved', '2026-02-03 20:35:44', '24', NULL, '4', 'Літературний вечір "Поезія Франківська"', '73', '2023-01-20');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Універсіада: Легка атлетика.', 'Золота медаль', 'approved', '2026-02-03 20:35:44', '7', NULL, '1', 'Універсіада: Легка атлетика', '74', '2025-04-09');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Google Hash Code (Hub PNU).', 'Топ-10 України', 'approved', '2026-02-03 20:35:45', '27', NULL, '3', 'Google Hash Code (Hub PNU)', '75', '2025-08-08');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Міжнародний хакатон NASA Space Apps.', 'Global Nominee', 'pending', '2026-02-03 20:35:45', '8', NULL, '5', 'Міжнародний хакатон NASA Space Apps', '76', '2026-11-01');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Кубок Ректора з футзалу.', '1 місце', 'approved', '2026-02-03 20:35:45', '20', NULL, '1', 'Кубок Ректора з футзалу', '77', '2023-08-06');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Еко-акція "Чисті Карпати".', 'Подяка від ректора', 'pending', '2026-02-03 20:35:45', '16', NULL, '6', 'Еко-акція "Чисті Карпати"', '78', '2026-05-14');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Студентська олімпіада з програмування.', 'Диплом 1 ступеня', 'approved', '2026-02-03 20:35:45', '17', NULL, '3', 'Студентська олімпіада з програмування', '79', '2026-07-03');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Найбільша кількість волонтерських годин.', 'Рекорд факультету', 'approved', '2026-02-03 20:35:45', '6', NULL, '6', 'Найбільша кількість волонтерських годин', '80', '2025-08-25');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Чемпіонат області з баскетболу.', '2 місце', 'approved', '2026-02-03 20:35:45', NULL, '1', '1', 'Чемпіонат області з баскетболу (Командний залік)', '81', '2026-05-20');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Танцювальний батл між факультетами.', 'Кубок глядачів', 'approved', '2026-02-03 20:35:45', '17', NULL, '4', 'Танцювальний батл між факультетами', '82', '2025-03-18');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Еко-акція "Чисті Карпати".', 'Подяка від ректора', 'pending', '2026-02-03 20:35:45', '18', NULL, '6', 'Еко-акція "Чисті Карпати"', '83', '2023-02-05');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Стажування в Європарламенті.', 'Успішно завершено', 'rejected', '2026-02-03 20:35:45', '4', NULL, '5', 'Стажування в Європарламенті', '84', '2025-07-06');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Google Hash Code (Hub PNU).', 'Топ-10 України', 'approved', '2026-02-03 20:35:45', '2', NULL, '3', 'Google Hash Code (Hub PNU)', '85', '2026-12-21');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Хакатон "Frankivsk Tech".', 'Гран-прі', 'approved', '2026-02-03 20:35:45', '23', NULL, '3', 'Хакатон "Frankivsk Tech"', '86', '2023-08-20');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Еко-акція "Чисті Карпати".', 'Подяка від ректора', 'approved', '2026-02-03 20:35:45', '19', NULL, '6', 'Еко-акція "Чисті Карпати"', '87', '2023-06-17');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Стажування в Європарламенті.', 'Успішно завершено', 'approved', '2026-02-03 20:35:45', '3', NULL, '5', 'Стажування в Європарламенті', '88', '2023-08-08');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Кубок Ректора з футзалу.', '1 місце', 'approved', '2026-02-03 20:35:46', '22', NULL, '1', 'Кубок Ректора з футзалу', '89', '2026-12-14');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Google Hash Code (Hub PNU).', 'Топ-10 України', 'approved', '2026-02-03 20:35:46', '19', NULL, '3', 'Google Hash Code (Hub PNU)', '90', '2025-09-08');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Еко-акція "Чисті Карпати".', 'Подяка від ректора', 'approved', '2026-02-03 20:35:46', NULL, '5', '6', 'Еко-акція "Чисті Карпати" (Командний залік)', '91', '2026-05-14');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Конкурс наукових робіт Фонду Пінчука.', 'Лауреат', 'approved', '2026-02-03 20:35:46', '11', NULL, '2', 'Конкурс наукових робіт Фонду Пінчука', '92', '2025-05-21');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Універсіада: Легка атлетика.', 'Золота медаль', 'approved', '2026-02-03 20:35:46', '27', NULL, '1', 'Універсіада: Легка атлетика', '93', '2026-06-09');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Erasmus+ Scholarship (Poland).', 'Отримано грант', 'rejected', '2026-02-03 20:35:46', '9', NULL, '5', 'Erasmus+ Scholarship (Poland)', '94', '2023-01-04');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Благодійний ярмарок на підтримку ЗСУ.', 'Зібрано 200 тис. грн', 'approved', '2026-02-03 20:35:46', '28', NULL, '6', 'Благодійний ярмарок на підтримку ЗСУ', '95', '2025-10-13');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Хакатон "Frankivsk Tech".', 'Гран-прі', 'approved', '2026-02-03 20:35:46', '3', NULL, '3', 'Хакатон "Frankivsk Tech"', '96', '2026-06-23');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Найбільша кількість волонтерських годин.', 'Рекорд факультету', 'rejected', '2026-02-03 20:35:46', '23', NULL, '6', 'Найбільша кількість волонтерських годин', '97', '2023-02-08');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Танцювальний батл між факультетами.', 'Кубок глядачів', 'approved', '2026-02-03 20:35:46', '9', NULL, '4', 'Танцювальний батл між факультетами', '98', '2026-06-03');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Турнір з шахів пам\'яті Стефаника.', 'Переможець', 'approved', '2026-02-03 20:35:46', '15', NULL, '1', 'Турнір з шахів пам\'яті Стефаника', '99', '2024-12-07');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Мовний конкурс імені Петра Яцика.', 'Переможець етапу', 'pending', '2026-02-03 20:35:46', '30', NULL, '2', 'Мовний конкурс імені Петра Яцика', '100', '2024-07-12');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Еко-акція "Чисті Карпати".', 'Подяка від ректора', 'pending', '2026-02-03 20:35:46', NULL, '1', '6', 'Еко-акція "Чисті Карпати" (Командний залік)', '101', '2026-09-04');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Erasmus+ Scholarship (Poland).', 'Отримано грант', 'approved', '2026-02-03 20:35:46', '28', NULL, '5', 'Erasmus+ Scholarship (Poland)', '102', '2023-09-12');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Голос Університету.', '1 місце', 'rejected', '2026-02-03 20:35:46', '9', NULL, '4', 'Голос Університету', '103', '2024-08-09');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Найбільша кількість волонтерських годин.', 'Рекорд факультету', 'approved', '2026-02-03 20:35:47', '9', NULL, '6', 'Найбільша кількість волонтерських годин', '104', '2023-11-15');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Літературний вечір "Поезія Франківська".', 'Відзнака', 'approved', '2026-02-03 20:35:47', '14', NULL, '4', 'Літературний вечір "Поезія Франківська"', '105', '2026-05-06');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Erasmus+ Scholarship (Poland).', 'Отримано грант', 'approved', '2026-02-03 20:35:47', '19', NULL, '5', 'Erasmus+ Scholarship (Poland)', '106', '2025-09-04');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Міжнародний хакатон NASA Space Apps.', 'Global Nominee', 'rejected', '2026-02-03 20:35:47', '31', NULL, '5', 'Міжнародний хакатон NASA Space Apps', '107', '2025-03-28');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Найбільша кількість волонтерських годин.', 'Рекорд факультету', 'pending', '2026-02-03 20:35:47', '8', NULL, '6', 'Найбільша кількість волонтерських годин', '108', '2023-09-08');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Студентська олімпіада з програмування.', 'Диплом 1 ступеня', 'approved', '2026-02-03 20:35:47', '31', NULL, '3', 'Студентська олімпіада з програмування', '109', '2023-02-28');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Благодійний ярмарок на підтримку ЗСУ.', 'Зібрано 200 тис. грн', 'pending', '2026-02-03 20:35:47', '12', NULL, '6', 'Благодійний ярмарок на підтримку ЗСУ', '110', '2026-12-15');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Наукова конференція молодих вчених.', 'Краща доповідь', 'rejected', '2026-02-03 20:35:47', NULL, '2', '2', 'Наукова конференція молодих вчених (Командний залік)', '111', '2025-09-27');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Універсіада: Легка атлетика.', 'Золота медаль', 'approved', '2026-02-03 20:35:47', '23', NULL, '1', 'Універсіада: Легка атлетика', '112', '2025-07-06');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Універсіада: Легка атлетика.', 'Золота медаль', 'approved', '2026-02-03 20:35:47', '11', NULL, '1', 'Універсіада: Легка атлетика', '113', '2026-12-11');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Міс ПНУ 2024.', 'Титул Міс Грація', 'approved', '2026-02-03 20:35:47', '8', NULL, '4', 'Міс ПНУ 2024', '114', '2024-12-05');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Турнір з шахів пам\'яті Стефаника.', 'Переможець', 'approved', '2026-02-03 20:35:47', '17', NULL, '1', 'Турнір з шахів пам\'яті Стефаника', '115', '2025-03-26');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Стажування в Європарламенті.', 'Успішно завершено', 'approved', '2026-02-03 20:35:47', '3', NULL, '5', 'Стажування в Європарламенті', '116', '2024-06-05');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Erasmus+ Scholarship (Poland).', 'Отримано грант', 'pending', '2026-02-03 20:35:47', '4', NULL, '5', 'Erasmus+ Scholarship (Poland)', '117', '2026-10-24');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Стажування в Європарламенті.', 'Успішно завершено', 'approved', '2026-02-03 20:35:48', '6', NULL, '5', 'Стажування в Європарламенті', '118', '2025-10-10');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Турнір з шахів пам\'яті Стефаника.', 'Переможець', 'approved', '2026-02-03 20:35:48', '5', NULL, '1', 'Турнір з шахів пам\'яті Стефаника', '119', '2024-03-15');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Google Hash Code (Hub PNU).', 'Топ-10 України', 'pending', '2026-02-03 20:35:48', '23', NULL, '3', 'Google Hash Code (Hub PNU)', '120', '2025-05-04');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Стажування в Європарламенті.', 'Успішно завершено', 'rejected', '2026-02-03 20:35:48', NULL, '1', '5', 'Стажування в Європарламенті (Командний залік)', '121', '2024-06-07');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Універсіада: Легка атлетика.', 'Золота медаль', 'rejected', '2026-02-03 20:35:48', '13', NULL, '1', 'Універсіада: Легка атлетика', '122', '2023-04-09');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Стажування в Європарламенті.', 'Успішно завершено', 'approved', '2026-02-03 20:35:48', '12', NULL, '5', 'Стажування в Європарламенті', '123', '2025-06-19');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Наукова конференція молодих вчених.', 'Краща доповідь', 'rejected', '2026-02-03 20:35:48', '10', NULL, '2', 'Наукова конференція молодих вчених', '124', '2025-08-28');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Найбільша кількість волонтерських годин.', 'Рекорд факультету', 'approved', '2026-02-03 20:35:48', '29', NULL, '6', 'Найбільша кількість волонтерських годин', '125', '2023-05-13');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Мовний конкурс імені Петра Яцика.', 'Переможець етапу', 'approved', '2026-02-03 20:35:48', '20', NULL, '2', 'Мовний конкурс імені Петра Яцика', '126', '2023-02-24');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Літературний вечір "Поезія Франківська".', 'Відзнака', 'approved', '2026-02-03 20:35:48', '11', NULL, '4', 'Літературний вечір "Поезія Франківська"', '127', '2026-08-09');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Міжнародний хакатон NASA Space Apps.', 'Global Nominee', 'rejected', '2026-02-03 20:35:48', '20', NULL, '5', 'Міжнародний хакатон NASA Space Apps', '128', '2023-01-15');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Студентська олімпіада з програмування.', 'Диплом 1 ступеня', 'rejected', '2026-02-03 20:35:48', '12', NULL, '3', 'Студентська олімпіада з програмування', '129', '2026-02-25');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Танцювальний батл між факультетами.', 'Кубок глядачів', 'pending', '2026-02-03 20:35:48', '18', NULL, '4', 'Танцювальний батл між факультетами', '130', '2026-03-16');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Голос Університету.', '1 місце', 'rejected', '2026-02-03 20:35:48', NULL, '2', '4', 'Голос Університету (Командний залік)', '131', '2026-05-18');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Найбільша кількість волонтерських годин.', 'Рекорд факультету', 'approved', '2026-02-03 20:35:48', '14', NULL, '6', 'Найбільша кількість волонтерських годин', '132', '2025-03-13');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Танцювальний батл між факультетами.', 'Кубок глядачів', 'rejected', '2026-02-03 20:35:48', '16', NULL, '4', 'Танцювальний батл між факультетами', '133', '2025-12-05');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Еко-акція "Чисті Карпати".', 'Подяка від ректора', 'approved', '2026-02-03 20:35:49', '7', NULL, '6', 'Еко-акція "Чисті Карпати"', '134', '2026-10-04');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Наукова конференція молодих вчених.', 'Краща доповідь', 'approved', '2026-02-03 20:35:49', '11', NULL, '2', 'Наукова конференція молодих вчених', '135', '2025-11-09');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Голос Університету.', '1 місце', 'rejected', '2026-02-03 20:35:49', '17', NULL, '4', 'Голос Університету', '136', '2024-05-17');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Еко-акція "Чисті Карпати".', 'Подяка від ректора', 'approved', '2026-02-03 20:35:49', '30', NULL, '6', 'Еко-акція "Чисті Карпати"', '137', '2025-11-07');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Стажування в Європарламенті.', 'Успішно завершено', 'approved', '2026-02-03 20:35:49', '16', NULL, '5', 'Стажування в Європарламенті', '138', '2026-03-21');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Турнір з шахів пам\'яті Стефаника.', 'Переможець', 'rejected', '2026-02-03 20:35:49', '27', NULL, '1', 'Турнір з шахів пам\'яті Стефаника', '139', '2024-04-03');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Erasmus+ Scholarship (Poland).', 'Отримано грант', 'rejected', '2026-02-03 20:35:49', '4', NULL, '5', 'Erasmus+ Scholarship (Poland)', '140', '2025-07-18');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Стажування в Європарламенті.', 'Успішно завершено', 'rejected', '2026-02-03 20:35:49', NULL, '4', '5', 'Стажування в Європарламенті (Командний залік)', '141', '2023-04-17');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Літературний вечір "Поезія Франківська".', 'Відзнака', 'approved', '2026-02-03 20:35:49', '2', NULL, '4', 'Літературний вечір "Поезія Франківська"', '142', '2023-05-24');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Голос Університету.', '1 місце', 'pending', '2026-02-03 20:35:49', '24', NULL, '4', 'Голос Університету', '143', '2023-12-05');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Голос Університету.', '1 місце', 'pending', '2026-02-03 20:35:49', '3', NULL, '4', 'Голос Університету', '144', '2024-03-13');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Турнір з шахів пам\'яті Стефаника.', 'Переможець', 'pending', '2026-02-03 20:35:49', '30', NULL, '1', 'Турнір з шахів пам\'яті Стефаника', '145', '2026-10-08');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Голос Університету.', '1 місце', 'approved', '2026-02-03 20:35:49', '18', NULL, '4', 'Голос Університету', '146', '2025-05-04');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Турнір з шахів пам\'яті Стефаника.', 'Переможець', 'approved', '2026-02-03 20:35:49', '26', NULL, '1', 'Турнір з шахів пам\'яті Стефаника', '147', '2026-07-24');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Стажування в Європарламенті.', 'Успішно завершено', 'approved', '2026-02-03 20:35:50', '28', NULL, '5', 'Стажування в Європарламенті', '148', '2024-04-03');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Універсіада: Легка атлетика.', 'Золота медаль', 'approved', '2026-02-03 20:35:50', '9', NULL, '1', 'Універсіада: Легка атлетика', '149', '2023-06-08');
INSERT INTO records (`description`, `result_value`, `status`, `created_at`, `user_id`, `team_id`, `category_id`, `title`, `id`, `event_date`) VALUES ('Студенти ПНУ показали високий рівень підготовки. Подія: Голос Університету.', '1 місце', 'approved', '2026-02-03 20:35:50', '3', NULL, '4', 'Голос Університету', '150', '2025-02-17');